In [74]:
import pandas as pd

df = pd.read_csv('data/games.csv')

In [80]:
df.isna().any()

year               False
home_team_id       False
away_team_id       False
home_player_1       True
home_player_2       True
                   ...
away_player_Y11     True
home_team_goal     False
away_team_goal     False
home_formations    False
away_formations    False
Length: 73, dtype: bool

In [93]:
home_formations_col = [col for col in df.columns if 'home_player_X' in col or 'home_player_Y' in col]
away_formations_col = [col for col in df.columns if 'away_player_X' in col or 'away_player_Y' in col]
df['home_formations'] = df[home_formations_col].apply(lambda col: list(col.values), axis=1)
df['away_formations'] = df[away_formations_col].apply(lambda col: list(col.values), axis=1)

In [96]:
# home_formations_col
df[home_formations_col]
df[away_formations_col]

,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,...,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11
0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,...,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0
1,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,...,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0
2,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,...,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0
3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,...,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0
4,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,...,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19322,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,4.0,6.0,...,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,9.0,11.0
19323,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,...,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0
19324,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,...,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0
19325,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,4.0,6.0,...,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,9.0,11.0
19326,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,...,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0

In [100]:
import hashlib

# Convert the list values to a unique integer using a hashing function
def list_to_int(lst):
    # Convert list to a string
    lst_str = str(lst)
    # Create a hash object
    hash_object = hashlib.md5(lst_str.encode())
    # Convert hash to an integer
    return int(hash_object.hexdigest(), 16)

df['home_formations'] = df['home_formations'].apply(list_to_int)

# Display the DataFrame with the converted column
print(df[['home_formations']])

                               home_formations
0       24078877818194080041850969372998440198
1       10091093975864003706667300854508678883
2      320677200815066161026595005017268629938
3       24078877818194080041850969372998440198
4       24078877818194080041850969372998440198
...                                        ...
19322  320066929391263699870520669457586799648
19323  320066929391263699870520669457586799648
19324  320066929391263699870520669457586799648
19325   53626947139224826668365096972799502223
19326  283360039814662200893425856429654602815

[19327 rows x 1 columns]

In [98]:
df[['home_formations']].nunique()

home_formations    375
dtype: int64

In [65]:
import matplotlib.pyplot as plt

# Extract home team player coordinates
home_player_X = df[[f'home_player_X{i}' for i in range(1, 12)]]
home_player_Y = df[[f'home_player_Y{i}' for i in range(1, 12)]]
home_player_X

,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11
0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0
1,1.0,2.0,4.0,8.0,6.0,2.0,4.0,6.0,8.0,4.0,6.0
2,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,6.0,4.0
3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0
4,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
19322,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0
19323,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0
19324,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0
19325,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0
19326,1.0,2.0,4.0,6.0,8.0,5.0,2.0,4.0,6.0,8.0,5.0